# Generated by Django 2.1.2 on 2018-10-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxcalculation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='assessment_year',
        ),
        migrations.RemoveField(
            model_name='person',
            name='department',
        ),
        migrations.RemoveField(
            model_name='person',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='person',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='income_year',
        ),
        migrations.RemoveField(
            model_name='person',
            name='joining_date',
        ),
    ]
