# Generated by Django 2.1.2 on 2018-10-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxcalculation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-created',)},
        ),
    ]
